version: '3.1'
volumes:
  DbCRM:
services:
  database:
    image: "postgres:13.3-alpine3.14"
    ports:
    - 5424:5432
    environment:
      POSTGRES_USER: crm_usr
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crm_db
      PGDATA: /data_db
    volumes:
    - DbCRM:/data_db