# Generated by Django 3.1.13 on 2021-08-04 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ سفارش'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('success', models.BooleanField(verbose_name='نتیجه')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیک')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
        ),
    ]
