# Generated by Django 3.2.5 on 2021-08-01 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='نام شرکت')),
                ('company_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='تلفن باید باکد استان باشد.مثال:08622222222', regex='^0[1-9]{2}[1-9][0-9]{7}$')], verbose_name='تلفن شرکت')),
                ('number_of_worker', models.IntegerField(verbose_name='تعداد کارگر')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('company_address', models.TextField(verbose_name='ادرس شرکت')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('mobile_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید یازده رقم باشد.مثال:09999999999', regex='^09[0-9]{9}$')], verbose_name='شماره موبایل')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیک')),
                ('company_registration_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت شرکت')),
                ('product', models.ManyToManyField(to='product.OrganizationProduct', verbose_name='محصولات تولیدی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ شروع گزارش کار')),
                ('last_data', models.DateField(auto_now=True, verbose_name=' تاریخ اخرین تغییرات')),
                ('title', models.CharField(max_length=150, verbose_name='موضوع گزارش کار')),
                ('status', models.CharField(choices=[('st', 'پیگیری در دست اقدام است'), ('in', 'پیگیری در حال جریان است'), ('ca', 'پیگیری منقضی شد'), ('fi', 'پیگیری تمام شد')], default='st', max_length=5, verbose_name='وضعیت پیگیری')),
                ('description', models.TextField(verbose_name='گزارش کار')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
        ),
    ]
