# Generated by Django 3.2.5 on 2021-08-01 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_catalog',
            field=models.ImageField(upload_to='img/', verbose_name='فایل کاتالوگ img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf_catalog',
            field=models.FileField(upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='فایل کاتالوگ pdf'),
        ),
    ]
